#!/bin/bash

# $Id$

# this file is part of ctan.tools bundle
# it is executed remotely (http://kyanh.net/)
# result is saved in /home/kyanhnet/www/ctan.tools/
#

msg()
{
	echo -e ":: $*"
}

msg "The time is $SECONDS"

mkdir -p /home/kyanhnet/www/ctan.tools/
cd /home/kyanhnet/www/ctan.tools/

msg "downloading the list of files..."
lynx -dump 'http://ctan.org/cgi-bin/filenameSearch.py?filename=.' > dump_files.txt

if [[ $? -gt 0 ]]; then
	msg "failed to download from CTAN. exit 1"
	rm -fv dump_files.txt
	exit 1
fi

msg "parsing dump_files.txt..."
msg "creating list of directories..."
grep tex-archive/ ./dump_files.txt \
	|sed -e 's/#/ /g' -e 's#http://ctan.org/tex-archive/# #g' \
	|gawk '{print $2}' |sort -u \
	> ./dirs.txt

msg "creating list of files..."
grep -E '^\[[0-9]+\][^ ]+' ./dump_files.txt \
	|gawk -F']' '{print $2}'\
	|sort -u \
	> ./files.txt

msg "creating cache.tar.bz2..."
tar -j -c -v -f cache.tar.bz2 dirs.txt files.txt

type lzma
if [[ $? == 0 ]]; then
	msg "creating cache.tar.lzma...."
	tar --use-compress-program lzma -c -v -f cache.tar.lzma dirs.txt files.txt
fi

msg "removing {dirs,files,dump_files}.txt as it is too big..."
rm -fv dump_files.txt dirs.txt files.txt

msg "The time is $SECONDS"

