#!/bin/bash

# $Id$

DESTDIR=$HOME/.ctan/
CTAN_ARCHIVE=http://ctan.org/tex-archive
CTAN_CONTRIB=$CTAN_ARCHIVE/macros/latex/contrib/
KYANHNET_REPOS=http://kyanh.net/ctan.tools/

msg()
{
	echo -e ":: $*"
}

ctan_update()
{
	if [[ "x$1" == "x-firsttime" ]]; then
		msg "This maybe the first time you use the tool. The directory ~/.ctan"
		msg "will be created and the tool tries to download some information from"
		msg "\t$CTAN_CONTRIB."
	fi

	mkdir -pv $DESTDIR

	msg "dumping $CTAN_CONTRIB..."
	lynx -dump $CTAN_CONTRIB > $DESTDIR/contrib.txt
	grep -E '^[ ]*\[[0-9]+\][^ ]+/' $DESTDIR/contrib.txt \
		|gawk '{printf("%s, %s\n", $1,$2);}' \
		|sed \
			-e 's/\/, /\t/g' \
			-e 's#\[[0-9]\+\]##g'	\
		> $DESTDIR/packages.txt

	msg "getting $KYANHNET_REPOS/ctan.tools/dump_files.tbz..."
	wget $KYANHNET_REPOS/cache.tbz -O $DESTDIR/cache.tbz
	msg "uncompressing $DESTDIR/cache.tbz..."
	tar xfj $DESTDIR/cache.tbz -C $DESTDIR

	msg "* Files updated: $DESTDIR/{files,contrib,packages,dirs}.txt"
	msg "* `wc -l $DESTDIR/packages.txt |gawk '{print $1}'` package(s) found"	
}

ctan_search()
{
	[[ -f $DESTDIR/packages.txt ]] || ctan_update -firsttime
	if [[ "x$1" == "x-file" ]]; then
		shift
		grep $* $DESTDIR/files.txt | grep -v obsolete
	else # search for package name	
		grep $* $DESTDIR/packages.txt | grep -v obsolete
	fi	
	if [[ $? -gt 0 ]]; then
		msg "not package/file found"
		return 1
	fi
}

ctan_get()
{
	ctan_search $* > $DESTDIR/tmp.txt
	if [[ $? -gt 0 ]]; then
		msg "not package matches '$*'"
		return
	fi
	if [[ "x$1" == "x-file" ]]; then
		shift
		ctan_grep_type='file'
	else
		ctan_grep_type='pkg'
	fi
	if [[ "$ctan_grep_type" == "file" ]]; then		
		for pkg in `cat $DESTDIR/tmp.txt`; do
			msg "$CTAN_ARCHIVE/$pkg";			
		done
		msg
		read -n 1 -p "Are you sure you want to download (y/N)?" download
		if [[ "x$download" == "xy" ]]; then
			msg
			for pkg in `cat $DESTDIR/tmp.txt`; do
				msg "downloading $pkg..."
				wget -c "$CTAN_ARCHIVE/$pkg";
			done				
		fi		
	else
		gawk '{print $1}' $DESTDIR/tmp.txt > $DESTDIR/tmp2.txt
		for pkg in `cat $DESTDIR/tmp2.txt`; do
			msg "$pkg\t $CTAN_CONTRIB/$pkg.zip";
		done
		msg
		read -n 1 -p "Are you sure you want to download (y/N)?" download
		if [[ "x$download" == "xy" ]]; then
			msg
			for f in `cat $DESTDIR/tmp2.txt`; do
				msg "downloading $pkg..."
				wget -c "$CTAN_CONTRIB/$pkg.zip";
			done	
		fi
	fi	
}

ctan_about()
{
	msg "ABOUT"
	msg
	msg "\tThis small tool is used to seach/download some LaTeX packages that were listed in CTAN:"
	msg "\t\t$CTAN_CONTRIB"
	msg "\tor search/download for any files in"
	msg "\t\t$CTAN_ARCHIVE/."
	msg ""
	msg "\tSince version 1.0.1, the tool will use the cache file"
	msg "\t\t$KYANHNET_REPOS/cache.tbz"
	msg "\tThis file contains the list of all files in CTAN. It's updated daily by a cron job hosted"
	msg "\tby http://kyanh.net/. The size of file is about 3MB (compressed) & 15MB (un-compressed)."
	msg
	msg "\tThe tool requires wget, lynx, gawk, wc, tar/bzip and sed program to run correctly."
	msg "\tSome linux distribution doesnot contains lynx by default and you must install lynx manually"
	msg "\tbefore running this script".
	msg
	msg "\tSo this tool requires a *nix-liked environment to work."
	msg
	msg "\tThis tool was written by kyanh <xkyanh@gmail.com>"
	msg "\tkyanh is a member of Vietnamese TeX Users Group <http://viettug.org>."
	msg "\tHe wrote this script as he wanted a fast client to access CTAN."
	msg
	msg "VERSION"
	msg
	msg	"\t1.0.0 2008/05/11: first version"
	msg	"\t1.1.0 2008/05/15: search for files (use cache file)"
	msg	"\t1.1.1 2008/05/15: fix bug (ctan_update)"
	msg "\t1.2.0 2008/05/16: smaller cache. Thanks to Karl Berry <karl@freefriends.org>"
	msg
	ctan_usage
	msg
	msg "TODO"
	msg
	msg "\t* package information supported"
	msg "\t* ability to select FTP mirror"
	msg "\t* search by package description,..."
	msg "\t* package build script"
	msg
	msg "LICENSE"
	msg
	msg "\tThis tool is published under LPPL."
	msg
	msg "BUGS"
	msg "\tFeel free to contact kyanh <xkyanh@gmail.com>. All feedback are welcome."
	msg
	
}

ctan_usage()
{
	msg "USAGE"
	msg
	msg "\tctan :\tshow all information about this tool"
	msg "\tctan update :\tupdate the package list (require lynx, wc, tar/bzip and internet connection)."
	msg "\tctan grep <string> :\tsearch packages match <string>. grep ability is supported."
	msg "\tctan get <string> :\tdownload packages match <string> to working directory."
	msg
	msg "\tIf you want to search for files:"
	msg
	msg "\tctan grep -file <string> :\tsearch for files."
	msg "\tctan get -file <string> :\tdownload files match <string> to working directory."
	msg
	msg "EXAMPLES"
	msg
	msg "\tctan grep theorem\t# search for packages match 'theorem'"
	msg "\tctan grep ^n\t# search for packages srated by 'n'"
	msg "\tctan get ^n\t# download packages started by 'n'"
	msg "\tctan get -file contrib/ntheorem.zip"
}

ctan_arg()
{
	if [[ "x$1" == "x" ]]; then
		msg "missing parameter"
		exit 1
	fi
}

if [[ "x$1" == "x" ]]; then
	ctan_about
elif [[ "x$1" == "xupdate" ]]; then
	ctan_update
elif [[ "x$1" == "xgrep" ]]; then
	shift
	ctan_arg $1
	ctan_search $*
elif [[ "x$1" == "xget" ]]; then
	shift
	ctan_arg $1
	ctan_get $*
else
	ctan_usage	
fi

